### ISSUE TITLE
Arduino configuration for LoRa transmit program

### ISSUE THREAD

**Issue by F4EWI** [Xinyuan-LilyGO/LilyGO-T-Echo#1]
I just received my T-Echo. I need a little help setting up my development environment correctly.
1) Installation of libraries

- **PCF8563_Library** -> can you give more details on which to use (link, version,...)?
- Same remark for the **SoftSPI** and **SerialFlash_ID539** ?

2) Compilation error

Arduino: 1.8.15 (Windows 10), Board: "Nordic nRF52840DK (PCA10056), S140 6.1.1, Level 0 (Release)"
Transmit:17:10: fatal error: GxDEPG0150BN/GxDEPG0150BN.h: No such file or directory
   17 | #include <GxDEPG0150BN/GxDEPG0150BN.h>  // 1.54" b/w
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1

GxDEPG0150BN/GxDEPG0150BN.h: No such file or directory

On my folder : C:\Users\HP\Documents\Arduino\libraries\GxEPD\src, I don't have this folder !

**Comment by LilyGO** [comment]
> I just received my T-Echo. I need a little help setting up my development environment correctly.
> 
> 1. Installation of libraries
> 
> * **PCF8563_Library** -> can you give more details on which to use (link, version,...)?
> * Same remark for the **SoftSPI** and **SerialFlash_ID539** ?
> 
> 1. Compilation error
> 
> Arduino: 1.8.15 (Windows 10), Board: "Nordic nRF52840DK (PCA10056), S140 6.1.1, Level 0 (Release)"
> Transmit:17:10: fatal error: GxDEPG0150BN/GxDEPG0150BN.h: No such file or directory
> 17 | #include <GxDEPG0150BN/GxDEPG0150BN.h> // 1.54" b/w
> | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> exit status 1
> 
> GxDEPG0150BN/GxDEPG0150BN.h: No such file or directory
> 
> On my folder : C:\Users\HP\Documents\Arduino\libraries\GxEPD\src, I don't have this folder !

The GxDEPG0150BN driver has been added. In [LilyGO-T-Echo/lib/GxEPD /](https://github.com/Xinyuan-LilyGO/LilyGO-T-Echo/tree/main/lib/GxEPD)
