### ISSUE TITLE
Bluetooth examples

### ISSUE THREAD

**Issue by F4EWI** [Xinyuan-LilyGO/LilyGO-T-Echo#10]
Did you have an example of a bluetooth program for the T-ECHO ?
Which library should I use?

**Comment by LilyGO** [comment]
Hello. [reference](https://github.com/Xinyuan-LilyGO/LilyGO-T-Echo#using-arduino-ide)，When you're done. Examples can be found under arduino IDE example
![1](https://user-images.githubusercontent.com/31160602/155248509-c55ea1d7-baa3-46e5-9396-346608173e72.png)
s

**Comment by F4EWI** [comment]
The idea is to have a T-Echo communicate with a T-Watch 2020 via Bluetooth. I found only examples with BLE (one way). What would be the best way to get there? 
SerialToSerialBT on the T-Echo ?

**Comment by LilyGO** [comment]
It has an example of BLE

**Comment by F4EWI** [comment]
Which ?

**Comment by LilyGO** [comment]
![1](https://user-images.githubusercontent.com/31160602/155840172-ebd33cdb-7a18-4270-bbd3-01a2acc1334c.png)
