### ISSUE TITLE
AS923-2

### ISSUE THREAD

**Issue by roomme13** [Xinyuan-LilyGO/LilyGO-T-Echo#11]
Is this available to use on 923mHz?

**Comment by LilyGO** [comment]
Carry SX1262. Officially, it's 150MHz to 960MHz

**Comment by roomme13** [comment]
based on specification it only state for 868/915, but my country use AS923 instead.  can i use it?
if you said based on SX1262, so what's different from two options 868/915 and 433/470? can i use 433/470 board and only change on firmware to 923mHz?

**Comment by LilyGO** [comment]
You need to use a suitable antenna
