### ISSUE TITLE
Programming a T-Echo with PlatformIO under Windows 10

### ISSUE THREAD

**Issue by F4EWI** [Xinyuan-LilyGO/LilyGO-T-Echo#12]
Do you have a tutorial that shows how to program a T-Echo under Windows 10 and Platformio environment?

**Comment by LilyGO** [comment]
https://github.com/Xinyuan-LilyGO/LilyGO-T-Echo#use-platformio

**Comment by F4EWI** [comment]
I need more than just a link. At first glance, some explanation is missing.
I may not have installed the correct version of J-Link??!!

![image](https://user-images.githubusercontent.com/74018524/158849832-2c74b1a5-5557-4ef1-afb2-aba7573486e9.png)

**Comment by LilyGO** [comment]
The J-link tool is required. As shown in figure https://github.com/Xinyuan-LilyGO/LilyGO-T-Echo/tree/main/bootloader#use-j-link-flash

**Comment by F4EWI** [comment]
Thank you for the informations. Which model of SWD interface are you using?

**Comment by LilyGO** [comment]
[reference](https://github.com/Xinyuan-LilyGO/LilyGO-T-Echo#use-platformio).  Article 5 Firmware can be downloaded via USB
