### ISSUE TITLE
DeepSleep power consumption

### ISSUE THREAD

**Issue by FabTangi** [Xinyuan-LilyGO/LilyGO-T-Echo#3]
Can we have detailed infos on the power consumption of the product? (working / deepsleep)

**Comment by LilyGO** [comment]
Working current: refer to https://github.com/lyusupov/SoftRF/wiki/Badge-Edition#battery-life
Sleep current: about 0.25mA

**Comment by FabTangi** [comment]
Thanks for your answer. I was expecting a few microA, according to datasheets of components. Do you have plan to reduce the consumption in deep-sleep?

**Comment by LilyGO** [comment]
Hi, There are no plans, and its sleep power consumption is already very low

**Comment by Llgok** [comment]
> Thanks for your answer. I was expecting a few microA, according to datasheets of components. Do you have plan to reduce the consumption in deep-sleep?

@FabTangi 
Hello, the latest low-power example has been updated. You can try using the example [Sleep\_Display](./examples/Sleep_Display) to reduce the power consumption of your onboard board.
