### ISSUE TITLE
Source code for the t-echo 1.2.42.753ae00-d.uf2 firmware 

### ISSUE THREAD

**Issue by runestone74** [Xinyuan-LilyGO/LilyGO-T-Echo#6]
Hi, I am sorry but I can't find the source code.

**Comment by runestone74** [comment]
We are eager to get the "reset without USB-power" working again :)

**Comment by LilyGO** [comment]
[Reference](https://github.com/meshtastic/Meshtastic-device)

**Comment by runestone74** [comment]
Thanks, I was searching for the source for this specific release: 1.2.42.753ae00-d where the "magic" reset button works as intended. Now it just works when USB power is plugged in. The UF2 files is available for download, but not the source code.

**Comment by LilyGO** [comment]
This is the source code for Meshtastic .  [Reference](https://github.com/meshtastic/Meshtastic-device)

**Comment by runestone74** [comment]
Yes but I can't find this specific release, do you have a direct link?

**Comment by LilyGO** [comment]
[Reference](https://github.com/meshtastic/Meshtastic-device/releases)

**Comment by runestone74** [comment]
There is no source code on github for release 1.2.42.753ae00-d can you search your backups and see if it turns up? :)

**Comment by runestone74** [comment]
It seems like the GPS functionality is working much more reliable as well. Can you please publish this source code, thanks!

**Comment by mkinney** [comment]
There are two software components: the bootloader (which is developed by the manufacturer LilyGO) and the firmware (could be made by anyone). I think, based on the version you're referencing, and the fact that they're pointing you to Meshtastic, I think you're looking for something like this: https://github.com/meshtastic/Meshtastic-device/releases/tag/v1.2.42.2759c8d

which is not made by LilyGo. It is made by the Meshtastic project (all volunteers)

However, that's fairly old in Meshtastic timeline. If you want to update to the latest, check out https://github.com/meshtastic/Meshtastic-device/releases/tag/v1.2.53.19c1f9f (or maybe the beta)

**Comment by runestone74** [comment]
Still no source from LilyGO, with the changes that makes the T-Echo able to wake from sleep/reset . Also probably some other GPS communication as well. Yes, we understand that you might not want to share the sourcecode, but could you please point us in the right direction in the way it should work, but dont. That would be appreciated.

**Comment by mkinney** [comment]
Check out this answer: https://github.com/Xinyuan-LilyGO/LilyGO-T-Echo/issues/9#issuecomment-1034425178

**Comment by mc-hamster** [comment]
@runestone74 here you go:

https://github.com/geeksville/Meshtastic-esp32/commit/753ae00
